spring.datasource.url=jdbc:postgresql://user-db:5432/user_db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

app.jwtSecret=8c6318da3103b17d9029e942f6b02668fcded6d917e077ff4e430c3d25e2b20c36e240cc921e3963eccc8c9cc2efeed231f1437507da95fab7f62d29fdf35b22
app.jwtExpirationInMs=86400000
