spring.application.name=discovery-server
server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
management.metrics.binder.jvm.enabled=false
management.metrics.binder.system.enabled=false
